// <auto-generated />
using System;
using Library_CaseStudy_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_CaseStudy_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_CaseStudy_MVC.Models.Book", b =>
                {
                    b.Property<int>("boodid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("boodid"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("availablecopiesnum")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("boodid");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Library_CaseStudy_MVC.Models.Borrow", b =>
                {
                    b.Property<int>("borrowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("borrowid"));

                    b.Property<int>("bookid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("borroedate")
                        .HasColumnType("date");

                    b.Property<int>("memberid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("returndate")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("borrowid");

                    b.HasIndex("bookid");

                    b.HasIndex("memberid");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("Library_CaseStudy_MVC.Models.Member", b =>
                {
                    b.Property<int>("memberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("memberid"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("memberid");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Library_CaseStudy_MVC.Models.Borrow", b =>
                {
                    b.HasOne("Library_CaseStudy_MVC.Models.Book", "Book")
                        .WithMany("borrows")
                        .HasForeignKey("bookid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_CaseStudy_MVC.Models.Member", "Member")
                        .WithMany("borrows")
                        .HasForeignKey("memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Library_CaseStudy_MVC.Models.Book", b =>
                {
                    b.Navigation("borrows");
                });

            modelBuilder.Entity("Library_CaseStudy_MVC.Models.Member", b =>
                {
                    b.Navigation("borrows");
                });
#pragma warning restore 612, 618
        }
    }
}
